# Use Node.js LTS (Long Term Support) version
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Define build arguments
ARG NODE_ENV=production
ARG DATABASE_CLIENT=mysql
ARG DATABASE_HOST=mysql
ARG DATABASE_PORT=3306
ARG DATABASE_NAME=strapi
ARG DATABASE_USERNAME=root
ARG DATABASE_PASSWORD=
ARG JWT_SECRET=your-super-secret-key
ARG ADMIN_JWT_SECRET=your-super-secret-key
ARG TRANSFER_TOKEN_SALT=your-super-secret-key
ARG APP_KEYS=your-super-secret-key
ARG PUBLIC_URL=http://localhost:1337
ARG DATABASE_SSL=true
ARG DATABASE_SSL_CAPATH=
ARG DATABASE_SSL_REJECT_UNAUTHORIZED=false
ARG DATABASE_SSL_CA=
ARG DATABASE_SSL_CERT=
ARG DATABASE_SSL_KEY=
ARG DATABASE_SSL_PASS=



# Set environment variables
ENV NODE_ENV=${NODE_ENV}
ENV DATABASE_CLIENT=${DATABASE_CLIENT}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
ENV TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
ENV APP_KEYS=${APP_KEYS}
ENV PUBLIC_URL=${PUBLIC_URL}
ENV DATABASE_SSL=${DATABASE_SSL}
ENV DATABASE_SSL_CAPATH=${DATABASE_SSL_CAPATH}
ENV DATABASE_SSL_REJECT_UNAUTHORIZED=${DATABASE_SSL_REJECT_UNAUTHORIZED}
ENV DATABASE_SSL_CA=${DATABASE_SSL_CA}
ENV DATABASE_SSL_CERT=${DATABASE_SSL_CERT}
ENV DATABASE_SSL_KEY=${DATABASE_SSL_KEY}
ENV DATABASE_SSL_PASS=${DATABASE_SSL_PASS}




# Copy only the necessary files
COPY package*.json ./
COPY config ./config
COPY database ./database
COPY public ./public
COPY src ./src
# COPY build ./build
COPY .env* ./
COPY ca.pem ./ca.pem


RUN npm install
RUN npm run build


# Expose the port Strapi runs on
EXPOSE 1337

# Start the application
CMD ["npm", "run", "start"] 